### ISSUE TITLE
Add default element for all parameters having a reasonable default

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#23]
For all parameters which must always get a specific value, please use the `default` (https://swagger.io/specification/v2/#parameter-object) field. This applies e.g. to all parameters named `Content-Type` (e.g. in https://github.com/AdobeDocs/cloudmanager-api-docs/blob/b6c0678a414f112dba41e3bc8ecbf324385cd20f/swagger-specs/api.yaml#L382)

**Comment by justinedelson** [comment]
@kwin Please correct me if I'm wrong, but my understanding of the swagger spec is that the `default` value is used when the client (in the case of a request) or server (in the case of a response) does *not* contain the specified key. What the swagger is representing here is that if there is no `Content-Type` header, that is an invalid request (since it is `required`). It is *not* representing that if there is no `Content-Type` header the `application/json` value is assumed.

**Comment by kwin** [comment]
Indeed

> Note: "default" has no meaning for required parameters.

Seems that there is no way to express in a swagger spec just for clients to generate hardcoded parameters.
